insert into EXCHANGE_VALUE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE)
values(10001,'USD','INR',65);
insert into EXCHANGE_VALUE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE)
values(10002,'EUR','INR',75);
insert into EXCHANGE_VALUE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE)
values(10003,'AUD','INR',25);