DROP TABLE IF EXISTS EXCHANGE_VALUE;

CREATE TABLE EXCHANGE_VALUE (
    ID BIGINT NOT NULL PRIMARY KEY,
    CONVERSION_MULTIPLE DECIMAL(19,2),
    CURRENCY_FROM VARCHAR(255),
    CURRENCY_TO VARCHAR(255)
);